export const ReservationActionTypes = {
  GET_RESERVATION_BEGINS: "GET_RESERVATION_BEGINS",
  GET_RESERVATION_SUCCESS: "GET_RESERVATION_SUCCESS",
  GET_RESERVATION_FAILURE: "GET_RESERVATION_FAILURE",

  GET_ALL_RESERVATIONS_BEGINS: "GET_ALL_RESERVATIONS_BEGINS",
  GET_ALL_RESERVATIONS_SUCCESS: "GET_ALL_RESERVATIONS_SUCCESS",
  GET_ALL_RESERVATIONS_FAILURE: "GET_ALL_RESERVATIONS_FAILURE",

  UPDATE_RESERVATION_BEGINS: "UPDATE_RESERVATION_BEGINS",
  UPDATE_RESERVATION_SUCCESS: "UPDATE_RESERVATION_SUCCESS",
  UPDATE_RESERVATION_FAILURE: "UPDATE_RESERVATION_FAILURE",

  DELETE_RESERVATION_BEGINS: "DELETE_RESERVATION_BEGINS",
  DELETE_RESERVATION_SUCCESS: "DELETE_RESERVATION_SUCCESS",
  DELETE_RESERVATION_FAILURE: "DELETE_RESERVATION_FAILURE",

  CREATE_RESERVATION_BEGINS: "CREATE_RESERVATION_BEGINS",
  CREATE_RESERVATION_SUCCESS: "CREATE_RESERVATION_SUCCESS",
  CREATE_RESERVATION_FAILURE: "CREATE_RESERVATION_FAILURE",
} as const;

export type ReservationActionType =
  (typeof ReservationActionTypes)[keyof typeof ReservationActionTypes];
